packages:
    - "apps/*"
    - "packages/*"

allowBuilds:
    "@scarf/scarf": true
    bcrypt: true
    esbuild: false
    unrs-resolver: false

autoInstallPeers: true

catalog:
    typescript: "~6.0.3"
    eslint: "^9.39.1"

nodeLinker: hoisted
virtualStoreDirMaxLength: 60
