import { Column, CreateDateColumn, Entity, JoinColumn, ManyToOne, PrimaryColumn } from "typeorm";
import { User } from "../../users/entities/user.entity";

@Entity("sessions")
export class Session {
    /** UUID generated by the application layer (crypto.randomUUID). */
    @PrimaryColumn("uuid")
    id!: string;

    @Column({ name: "user_id" })
    userId!: string;

    @ManyToOne(() => User, (user) => user.sessions, { onDelete: "CASCADE" })
    @JoinColumn({ name: "user_id" })
    user!: User;

    /** bcrypt hash of the raw refresh JWT. */
    @Column({ name: "refresh_token_hash", length: 255 })
    refreshTokenHash!: string;

    @Column({ name: "user_agent", length: 500, nullable: true })
    userAgent!: string | null;

    @Column({ name: "ip_address", length: 45, nullable: true })
    ipAddress!: string | null;

    @Column({ name: "expires_at", type: "timestamptz" })
    expiresAt!: Date;

    @CreateDateColumn({ name: "created_at" })
    createdAt!: Date;
}
